name: DAST Scan (PyGoat)

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PyGoat Docker image
      run: docker build -t pygoat:latest .

    - name: Run PyGoat container
      run: |
        docker run -d --name pygoat-app -p 3000:3000 pygoat:latest
        sleep 15

    - name: Check if PyGoat is reachable
      run: curl -I http://localhost:3000 || echo "PyGoat is not responding"

    - name: ZAP Scan using GitHub Action
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'http://localhost:3000'
        docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

    - name: Stop and remove PyGoat container
      run: docker rm -f pygoat-app || true
