name: DAST Scan Only (PyGoat)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dast:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build PyGoat Docker image
      run: docker build -t pygoat:latest .

    - name: Run PyGoat container
      run: |
        docker run -d --name pygoat-app -p 8000:8000 pygoat:latest
        sleep 15  # Czekaj aż aplikacja się uruchomi

    - name: Check if PyGoat is reachable
      run: curl -I http://localhost:8000 || echo "❌ PyGoat is not responding"

    - name: Run OWASP ZAP DAST scan
      run: |
        docker run --rm --link pygoat-app:pygoat \
          ghcr.io/zaproxy/zap-stable zap-baseline.py \
          -t http://pygoat:8000 \
          -r zap_pygoat_report.html \
          -J zap_pygoat_report.json

    - name: Show PyGoat logs (on failure)
      if: failure()
      run: docker logs pygoat-app

#    - name: Upload ZAP HTML report
#      uses: actions/upload-artifact@v4
#      with:
#          name: zap-report-html
#          path: zap_pygoat_report.html

    - name: Stop and remove PyGoat container
      run: docker rm -f pygoat-app
