name: DAST Scan (PyGoat)

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build PyGoat Docker image
      run: docker build -t pygoat:latest .

    - name: Run PyGoat container
      run: |
        docker run -d --name pygoat-app -p 8000:8000 pygoat:latest
        sleep 15

    - name: Check if PyGoat is reachable
      run: curl -I http://localhost:8000 || echo "PyGoat is not responding"

    - name: ZAP Scan using GitHub Action
      uses: zaproxy/action-baseline@v0.14.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target: 'http://localhost:8000'
        docker_name: 'owasp/zap2docker-stable'
        cmd_options: '-a -J zap_report.json -r zap_report.html'

    - name: Stop and remove PyGoat container
      run: docker rm -f pygoat-app || true
