name: SCA scan for PyGoat

on: [push]

jobs:
  depcheck_sca:
    runs-on: ubuntu-latest
    name: Dependency-Check SCA Scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: depcheck
        with:
          project: 'PyGoat'
          path: '.'  # scan entire project
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired
            --scan requirements.txt
            --project PyGoat

      - name: Upload DepCheck Report
        uses: actions/upload-artifact@v3
        with:
          name: DepCheck HTML Report
          path: reports
