name: Secrets Scan

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  secrets-scan:
    name: Gitleaks Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Potrzebne do pełnego skanowania historii gita

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Poniższy wpis wymagany tylko w organizacjach GitHub z licencją
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
