name: DevSecOps Secrets Scan for PyGoat

on:
  workflow_dispatch: 

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for comprehensive scanning

      # Run TruffleHog for secrets scanning
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3
        with:
          args: --json --output=trufflehog-report.json
        continue-on-error: true # Continue to allow reporting even if secrets are found

      # Convert TruffleHog output to SARIF format
      - name: Convert TruffleHog output to SARIF
        run: |
          docker run --rm -v $(pwd):/workspace ghcr.io/trufflesecurity/trufflehog-sarif:latest /workspace/trufflehog-report.json > trufflehog.sarif
        if: always()

      # Upload TruffleHog results to GitHub Security tab
      - name: Upload TruffleHog SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog.sarif
        if: always()

      # Notify on secrets detection
      - name: Notify on secrets found
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: 'security-alerts'
          text: 'Secrets detected in PyGoat repository. Review GitHub Security tab for details.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
